name: 5XSK0
channels:
  - conda-forge
  # - nvidia
  - pytorch
dependencies:
  - python = 3.10
  # - cudatoolkit=11.6 # disable this if on a mac  
  - matplotlib
  - numpy
  - pytest
  - nbformat
  - jupyter
  - tqdm
  - pandas
  - pytorch::pytorch
  - pytorch::torchvision
  # - pytorch::torchaudio
  - conda-forge::imgaug
  - conda-forge::albumentations
